data:
    name: megadepth
    train_split: superglue2_train_scenes.txt
    val_split: superglue2_valid_scenes.txt
    val_num_per_scene: 200
    resize: 1280
    resize_by: max
    pad: 1280
    two_view: true
    min_overlap: 0.1
    max_overlap: 1.0
    sort_by_overlap: false
    shuffle_training: true
    train_num_per_scene: 400
    batch_size: 24
    num_workers: 16
    load_features:
        do: True
        export_name: SP-nms3-n2048_megadepth-undist-r1024
        max_num_keypoints: 1024
        force_num_keypoints: true
        load_descriptors: true
model:
    name: two_view_pipeline
    extractor:
        name: null
    detector:
        name: null
    descriptor:
        name: null
    ground_truth:
        from_pose_depth: true
        th_positive: 3
        th_negative: 5
    matcher:
        name: superglue_v1
        weights: null
        input_dim: 256
        descriptor_dim: 256
        GNN_layers: [
            self, cross, self, cross, self, cross,
            self, cross, self, cross, self, cross,
            self, cross, self, cross, self, cross,
        ]
        #output_normalization: double_softmax
        output_normalization: sinkhorn
        num_sinkhorn_iterations: 40
        checkpointed: true
        loss:
            nll_balancing: 0.5
train:
    seed: 0
    epochs: 200
    log_every_iter: 100
    eval_every_iter: 500
    dataset_callback_fn: sample_new_items
    lr: 0.0001
    lr_schedule:
        start: 250e3
        type: exp
        exp_div_10: 50e3
    median_metrics: [match_recall]
